product/urls.py
from django.conf.urls import url
from .views import IndexView, CategoryListView, ProductListView, ProductDetailView, LastAdded


app_name = 'products'
urlpatterns = [
    url(r'^products/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='product'),
    url(r'^products/(?P<slug>[\w-]+)/$', ProductListView.as_view(), name='productslist'),
    url(r'^products/$', CategoryListView.as_view(), name='categories'),
    url(r'^lastadded/', LastAdded.as_view(), name='lastadded'),
    url(r'^$', IndexView.as_view(), name='indexview'),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls'), {'template_name': 'product/login.html'}),
    url(r'^', include('product.urls')),

]

product/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=10000)

    def __str__(self):
        return self.name


class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE,)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=10000)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

product/views.py
from django.shortcuts import get_object_or_404
from .models import Category, Product
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import Http404
from django.views.generic import ListView, DetailView
import datetime


class IndexView(ListView):
    context_object_name = 'home_list'
    template_name = 'itemslist.html'
    queryset = Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context


class CategoryListView(ListView):
    model = Category
    template_name = 'categorylist.html'


class ProductListView(ListView):
    model = Product
    template_name = 'productslist.html'

    def get_queryset(self, *args, **kwargs):
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        if not category:
            raise Http404
        return Product.objects.filter(category=category.id)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'productditail.html'

    def get_object(self, *args, **kwargs):
        category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        if not category:
            raise Http404
        return Product.objects.get(slug=self.kwargs['slug'])


@method_decorator(login_required, name='dispatch')
class LastAdded(ListView):
    model = Product
    queryset = Product.objects.filter(created_at__gt=datetime.datetime.now() - datetime.timedelta(hours=24))
    template_name = 'lastadded.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LastAdded, self).dispatch(*args, **kwargs)

product/templates/product/categorylist.html
{% extends 'index.html' %}

{% block title %}Categories{% endblock %}

{% block content %}
    <ul>
    {% for category in object_list %}
        <li>
            <p><a href="{% url 'products:productslist' category.slug %}">{{ category.name }}</a></p>
            <p>Slug: {{ category.slug }}</p>
            <p>Description: {{ category.description }}</p>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

product/templates/product/itemslist.html
{% extends 'index.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h3>Categories:</h3>
    {% for item in home_list %}
        <ul>
            <li>
                {{ item }}
            </li>
        </ul>
    {% endfor %}
    <h3>Products:</h3>
    {% for item in products %}
        <ul>
            <li>
                {{ item }}
            </li>
        </ul>
    {% endfor %}
{% endblock %}

product/templates/product/lastadded.html
{% extends 'index.html' %}

{% block title %}Added in 24 hours{% endblock %}

{% block content %}
    {% if masseg %}
        <h3>{{ masseg }}</h3>
    {% endif %}
    {% for product in object_list %}
        <ul>
        <li>{{ product }}</li>
        </ul>
    {% endfor %}
{% endblock %}

product/templates/product/login.html
{% extends "index.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

product/templates/product/productditail.html
{% extends 'index.html' %}

{% block content %}
    <p>{{ product.name }}</p>
    <p>{{ product.description }}</p>
    <p>{{ product.price }}</p>

{% endblock %}

product/templates/product/productslist.html
{% extends 'index.html' %}

{% block title %}{% endblock %}

{% block content %}
    {% for product in object_list %}
        <p><a href="{% url 'products:product' product.category product.slug %}">{{ product.name }}</a></p>
        <p>{{ product.description }}</p>
        <p>{{ product.price }}</p>
    {% endfor %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>